//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AbleProject_Empty.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobDetail
    {
        public int JobId { get; set; }
        public string JobRole { get; set; }
        public string JobDescription { get; set; }
        public string Address { get; set; }
        public int Phone { get; set; }
        public System.DateTime PostedOn { get; set; }
    }
}
