//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AbleProject_Empty.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResumeDetail
    {
        public int StudentId { get; set; }
        public string StudentName { get; set; }
        public string Email { get; set; }
        public string Contact { get; set; }
        public string School { get; set; }
        public string PlusTwoPercentage { get; set; }
        public string College { get; set; }
        public string Branch { get; set; }
        public string GraduationPercentage { get; set; }
        public string Backlogs { get; set; }
        public string Description { get; set; }
        public System.DateTime PostedOn { get; set; }
    }
}
